version: '2.1'
orbs:
  python: circleci/python@1.5.0
  browser-tools: circleci/browser-tools@1.2.3
jobs:
  test:
    docker:
      - image: 'cimg/python:3.7.5-browser'
    steps:
      # install the latest versions
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          command: |
            google-chrome --version
            chromedriver --version
          name: Check install
      - run:
          command: |
            curl -o rcc https://downloads.robocorp.com/rcc/releases/latest/linux64/rcc
            chmod a+x rcc
            sudo mv rcc /usr/local/bin/
            rcc --version
          name: install RCC
      - run:
          command: |
            rcc run
    workflows: null
