version: '2.1'
orbs:
  python: circleci/python@1.5.0
  browser-tools: circleci/browser-tools@1.2.3
jobs:
  test:
    docker:
      - image: 'cimg/python:3.7.5-browser'
    steps:
      # install the latest versions
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          command: |
            google-chrome --version
            chromedriver --version
          name: Check install
workflows: null


version: 2.1
orbs:
  python: circleci/python@1.5.0
jobs:
  build:
    docker:
      - image: cimg/python:3.7.5
    steps:
      - checkout
      - run:
          name: Run using RCC?
          command: |
            pipenv run python manage.py test
      # - store_test_results:
      #     path: test-results
      # - store_artifacts:
      #     path: test-results
      #     destination: tr1